/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Tielin) {
      root.Tielin = {};
    }
    root.Tielin.Likes = factory(root.Tielin.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Likes model module.
   * @module model/Likes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Likes</code>.
   * 
   * @alias module:model/Likes
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Likes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Likes} obj Optional instance to populate.
   * @return {module:model/Likes} The populated <code>Likes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('source_player_id'))
        obj.sourcePlayerId = ApiClient.convertToType(data['source_player_id'], 'Number');
      if (data.hasOwnProperty('dest_player_id'))
        obj.destPlayerId = ApiClient.convertToType(data['dest_player_id'], 'Number');
      if (data.hasOwnProperty('round_num'))
        obj.roundNum = ApiClient.convertToType(data['round_num'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} sourcePlayerId
   */
  exports.prototype.sourcePlayerId = undefined;

  /**
   * @member {Number} destPlayerId
   */
  exports.prototype.destPlayerId = undefined;

  /**
   * @member {Number} roundNum
   */
  exports.prototype.roundNum = undefined;

  /**
   * 
   * @member {String} action
   */
  exports.prototype.action = undefined;

  return exports;

}));
