/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Tielin) {
      root.Tielin = {};
    }
    root.Tielin.Profiles = factory(root.Tielin.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Profiles model module.
   * @module model/Profiles
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Profiles</code>.
   * 
   * @alias module:model/Profiles
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Profiles</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Profiles} obj Optional instance to populate.
   * @return {module:model/Profiles} The populated <code>Profiles</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('is_robot'))
        obj.isRobot = ApiClient.convertToType(data['is_robot'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('waifu_image_url'))
        obj.waifuImageUrl = ApiClient.convertToType(data['waifu_image_url'], 'String');
      if (data.hasOwnProperty('hearts'))
        obj.hearts = ApiClient.convertToType(data['hearts'], 'Number');
      if (data.hasOwnProperty('implants'))
        obj.implants = ApiClient.convertToType(data['implants'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Boolean} isRobot
   */
  exports.prototype.isRobot = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} waifuImageUrl
   */
  exports.prototype.waifuImageUrl = undefined;

  /**
   * @member {Number} hearts
   */
  exports.prototype.hearts = undefined;

  /**
   * @member {Number} implants
   */
  exports.prototype.implants = undefined;

  return exports;

}));
