/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tielin);
  }
}(this, function(expect, Tielin) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Likes', function() {
      beforeEach(function() {
        instance = new Tielin.Likes();
      });

      it('should create an instance of Likes', function() {
        // TODO: update the code to test Likes
        expect(instance).to.be.a(Tielin.Likes);
      });

      it('should have the property sourcePlayerId (base name: "source_player_id")', function() {
        // TODO: update the code to test the property sourcePlayerId
        expect(instance).to.have.property('sourcePlayerId');
        // expect(instance.sourcePlayerId).to.be(expectedValueLiteral);
      });

      it('should have the property destPlayerId (base name: "dest_player_id")', function() {
        // TODO: update the code to test the property destPlayerId
        expect(instance).to.have.property('destPlayerId');
        // expect(instance.destPlayerId).to.be(expectedValueLiteral);
      });

      it('should have the property roundNum (base name: "round_num")', function() {
        // TODO: update the code to test the property roundNum
        expect(instance).to.have.property('roundNum');
        // expect(instance.roundNum).to.be(expectedValueLiteral);
      });

      it('should have the property action (base name: "action")', function() {
        // TODO: update the code to test the property action
        expect(instance).to.have.property('action');
        // expect(instance.action).to.be(expectedValueLiteral);
      });

    });
  });

}));
