/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tielin);
  }
}(this, function(expect, Tielin) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PickupLines', function() {
      beforeEach(function() {
        instance = new Tielin.PickupLines();
      });

      it('should create an instance of PickupLines', function() {
        // TODO: update the code to test PickupLines
        expect(instance).to.be.a(Tielin.PickupLines);
      });

      it('should have the property playerId (base name: "player_id")', function() {
        // TODO: update the code to test the property playerId
        expect(instance).to.have.property('playerId');
        // expect(instance.playerId).to.be(expectedValueLiteral);
      });

      it('should have the property roundNum (base name: "round_num")', function() {
        // TODO: update the code to test the property roundNum
        expect(instance).to.have.property('roundNum');
        // expect(instance.roundNum).to.be(expectedValueLiteral);
      });

      it('should have the property earnedSwipesLeft (base name: "earned_swipes_left")', function() {
        // TODO: update the code to test the property earnedSwipesLeft
        expect(instance).to.have.property('earnedSwipesLeft');
        // expect(instance.earnedSwipesLeft).to.be(expectedValueLiteral);
      });

      it('should have the property earnedSwipesRight (base name: "earned_swipes_right")', function() {
        // TODO: update the code to test the property earnedSwipesRight
        expect(instance).to.have.property('earnedSwipesRight');
        // expect(instance.earnedSwipesRight).to.be(expectedValueLiteral);
      });

      it('should have the property humanWords (base name: "human_words")', function() {
        // TODO: update the code to test the property humanWords
        expect(instance).to.have.property('humanWords');
        // expect(instance.humanWords).to.be(expectedValueLiteral);
      });

      it('should have the property robotWords (base name: "robot_words")', function() {
        // TODO: update the code to test the property robotWords
        expect(instance).to.have.property('robotWords');
        // expect(instance.robotWords).to.be(expectedValueLiteral);
      });

    });
  });

}));
