/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tielin);
  }
}(this, function(expect, Tielin) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Profiles', function() {
      beforeEach(function() {
        instance = new Tielin.Profiles();
      });

      it('should create an instance of Profiles', function() {
        // TODO: update the code to test Profiles
        expect(instance).to.be.a(Tielin.Profiles);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property isRobot (base name: "is_robot")', function() {
        // TODO: update the code to test the property isRobot
        expect(instance).to.have.property('isRobot');
        // expect(instance.isRobot).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property waifuImageUrl (base name: "waifu_image_url")', function() {
        // TODO: update the code to test the property waifuImageUrl
        expect(instance).to.have.property('waifuImageUrl');
        // expect(instance.waifuImageUrl).to.be(expectedValueLiteral);
      });

      it('should have the property hearts (base name: "hearts")', function() {
        // TODO: update the code to test the property hearts
        expect(instance).to.have.property('hearts');
        // expect(instance.hearts).to.be(expectedValueLiteral);
      });

      it('should have the property implants (base name: "implants")', function() {
        // TODO: update the code to test the property implants
        expect(instance).to.have.property('implants');
        // expect(instance.implants).to.be(expectedValueLiteral);
      });

    });
  });

}));
