/*
 * TIELIN
 * Tech is evil Love is not
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Likes', 'model/PickupLines', 'model/Profiles', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Likes'), require('./model/PickupLines'), require('./model/Profiles'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Likes, PickupLines, Profiles, DefaultApi) {
  'use strict';

  /**
   * Tech_is_evil_Love_is_not.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Tielin = require('index'); // See note below*.
   * var xxxSvc = new Tielin.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Tielin.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Tielin.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Tielin.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Likes model constructor.
     * @property {module:model/Likes}
     */
    Likes: Likes,
    /**
     * The PickupLines model constructor.
     * @property {module:model/PickupLines}
     */
    PickupLines: PickupLines,
    /**
     * The Profiles model constructor.
     * @property {module:model/Profiles}
     */
    Profiles: Profiles,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
